namespace DailyExpenses.Api.DTOs;

/// <summary>
/// Response model for budget data.
/// Contains all budget properties including generated ID and timestamps.
/// </summary>
public record BudgetResponse
{
    /// <summary>
    /// Unique identifier for the budget (generated by system).
    /// </summary>
    public required Guid Id { get; init; }

    /// <summary>
    /// ID of the user who owns this budget.
    /// </summary>
    public required Guid UserId { get; init; }

    /// <summary>
    /// Month for which this budget applies (first day of month, UTC date).
    /// Example: "2026-01-01T00:00:00Z"
    /// </summary>
    public required DateTime Month { get; init; }

    /// <summary>
    /// Budget amount in VND.
    /// Example: 15000000 (15 million VND)
    /// </summary>
    public required decimal Amount { get; init; }

    /// <summary>
    /// Timestamp when the budget was created (UTC).
    /// Example: "2026-01-15T10:30:00Z"
    /// </summary>
    public required DateTime CreatedAt { get; init; }
}
