namespace DailyExpenses.Api.DTOs;

/// <summary>
/// Response model for expense data.
/// Contains all expense properties including generated ID and timestamps.
/// </summary>
public record ExpenseResponse
{
    /// <summary>
    /// Unique identifier for the expense (generated by system).
    /// </summary>
    public required Guid Id { get; init; }

    /// <summary>
    /// ID of the user who owns this expense.
    /// </summary>
    public required Guid UserId { get; init; }

    /// <summary>
    /// Expense amount in VND.
    /// </summary>
    public required decimal Amount { get; init; }

    /// <summary>
    /// Optional note describing the expense.
    /// </summary>
    public string? Note { get; init; }

    /// <summary>
    /// Date of the expense (UTC date, time component is always 00:00:00).
    /// </summary>
    public required DateTime Date { get; init; }

    /// <summary>
    /// Timestamp when the expense was created (UTC).
    /// </summary>
    public required DateTime CreatedAt { get; init; }

    /// <summary>
    /// Timestamp when the expense was last updated (UTC).
    /// </summary>
    public required DateTime UpdatedAt { get; init; }
}
